#!/bin/bash
set -e

REGISTRY=$1
ORGANIZATION=$2
IMAGE_NAME=$3
VERSION=$4
REGISTRY_USER=$5
REGISTRY_TOKEN=$6

docker login --password "${REGISTRY_TOKEN}" --username "${REGISTRY_USER}" ${REGISTRY}

MAJOR=$(echo $VERSION | tr  '.' "\n" | sed -n 1p)
MINOR=$(echo $VERSION | tr  '.' "\n" | sed -n 2p)
echo "building $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR}"
docker build -t $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR} --no-cache .
docker push $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR}
docker tag $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR} $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR}.${MINOR}
docker push $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR}.${MINOR}
docker tag $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR} $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${VERSION}
docker push $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${VERSION}
docker tag $REGISTRY/$ORGANIZATION/$IMAGE_NAME:${MAJOR} $REGISTRY/$ORGANIZATION/$IMAGE_NAME:latest
docker push $REGISTRY/$ORGANIZATION/$IMAGE_NAME:latest
