---
browserSettings:
  changeTeamNames: true
  changeProgressionDefinition: true


teamProgressFile: 'team-progress-default.yaml' 
progressDefinition:
  Not implemented:
    score: 0%
    definition: Activity not started and not planned
  Backlog:
    score: 20%
    definition: Activity has been put in the backlog but not yet started
  Started:
    score: 40%
    definition: Activity has been started and is partly implemented
  Fully implemented:
    score: 100%
    definition: Fully implemented

teams: 
  $ref: 'default/teams.yaml#/teams'
teamGroups:
  $ref: 'default/teams.yaml#/teamGroups'

activityFiles:
    # - generated/generated.yaml 
    - default/activities.yaml 
    # - custom/custom-activities.yaml  # For customizing your own activities


#
# Various strings and messages
#
lang: en
strings:
  en:
    allTeamsGroupName: 'All teams'
    maturityLevels:
      [
        'Level 1: Basic understanding of security practices',
        'Level 2: Adoption of basic security practices',
        'Level 3: High adoption of security practices',
        'Level 4: Very high adoption of security practices',
        'Level 5: Advanced deployment of security practices at scale',
      ]
    labels: ['Very Low', 'Low', 'Medium', 'High', 'Very High']
    knowledgeLabels:
      [
        'Very Low (one discipline)',
        'Low (one discipline)',
        'Medium (two disciplines)',
        'High (two disciplines)',
        'Very High (three or more disciplines)',
      ]
